
import type { Metadata } from "next";
import "./globals.css";
import { Sessionprovider } from "@/providers/SessionProvider";
import { Inter as FontSans } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Sessionprovider>
      <body
        className={`${fontSans.variable} antialiased`}
      >
        {children}
        <Toaster/>
      </body>
      </Sessionprovider>
    </html>
  );
}
