import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sessionprovider } from "@/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Sessionprovider>
      <body
        className={`${inter.className} antialiased`}
      >
        {children}
      </body>
      </Sessionprovider>
    </html>
  );
}
